
import:
    data:
        from: timeflow.File
        filename: time-series.csv
    routine: timeflow.CSV
    map:
        DateTime: time
        Temperature: temperature
    const:
        description: bs


select:
    data:
        from: import
    routine: timeflow.Threshold
    column: temperature
    filter: ">"
    value: 15.2
