
rename:
    routine: timeflow.Rename
    data:
        source: time-series.csv
    columns:
        DateTime: time
        Temperature: temperature


warm:
    routine: timeflow.BooleanFilter
    data:
        source: import
        get: new
    column: temperature
    operator: ">"
    value: 15.2


# $ timeflow workflow.yaml warm csv


save:
    routine: timeflow.Save
    data:
        source: warm
        get: true
    save_as: time-series-warm.csv


# $ timeflow workflow.yaml
