
map_cols:
    routine: timeflow.MapColumns
    data:
        source: time-series.csv
    map:
        DateTime: time
        Temperature: temperature
    const:
        description: bs


warm:
    routine: timeflow.BoolFilter
    data:
        source: import
    column: temperature
    operator: ">"
    value: 15.2

# run with
# timeflow workflow.yaml select_clear -o time-series-out.csv -t csv

# save:
#     routine: timeflow.CSVExport
#     data:
#         source: warm
#         if: true
#     save_to: time-series-out.csv
