
import:
    routine: timeflow.CSVImport
    data:
        source: timeflow.File
        filename: time-series.csv
    map:
        DateTime: time
        Temperature: temperature
    const:
        description: bs


select_clear:
    routine: timeflow.BoolFilter
    data:
        source: import
    column: temperature
    operator: ">"
    value: 15.2


save:
    routine: timeflow.CSVExport
    data:
        source: select
        if: true
