
rename:
    routine: timeflow.Rename
    data_from:
        source: time-series.csv
    columns:
        DateTime: time
        Temperature: temperature


warm:
    routine: timeflow.BooleanFilter
    data_from:
        source: rename
    new_column: warm
    filter_column: temperature
    operator: ">="
    value: 15.4


meta:
    routine: timeflow.ConstantColumns
    data_from:
        source: warm
        filter: warm
    constants:
        its: not cool


merged:
    routine: timeflow.Passthrough
    data_from:
        source: rename
        merge:
            source: meta
            how: left
            copy: false


# $ timeflow workflow.yaml -r meta


# save:
#     routine: timeflow.Save
#     data:
#         source: warm
#         get: true
#     save_as: time-series-warm.csv


# $ timeflow workflow.yaml
