
rename:
    routine: timeflow.Rename
    data_from:
        source: time-series.csv
    columns:
        DateTime: time
        Temperature: temperature


warm:
    routine: timeflow.BooleanFilter
    data_from:
        source: rename
        get: new
    column: temperature
    operator: ">="
    value: 15.4


# $ timeflow workflow.yaml warm


# save:
#     routine: timeflow.Save
#     data:
#         source: warm
#         get: true
#     save_as: time-series-warm.csv


# $ timeflow workflow.yaml
